[AUC-3] Typography
Trevoule/AuctionBid pull request #3
Opened 2022-02-23 15:54 UTC by Trevoule

added responsive fonts for the typography default theme

2022-02-25 07:38 UTC, sergeevds requested changes

2022-03-04 09:23 UTC, Trevoule commented on react/src/components/Material/theme.js
> +        // [theme.breakpoints.up("md")]: {
fixed

2022-03-04 09:23 UTC, Trevoule commented on react/src/components/Material/theme.js
> +  // components: {
fixed

2022-03-04 09:23 UTC, Trevoule commented on react/src/components/Typography/stories.js
> +const useStyles = makeStyles((theme) => ({
fixed

2022-03-04 09:23 UTC, Trevoule commented on react/src/components/Typography/stories.js
> +        <Typography variant="h2" component="h2" className={classes.DesktopL}>
fixed

2022-03-04 20:36 UTC, sergeevds commented on react/src/components/Material/theme.js
> +  breakpoints: {
looks like default. If we didn't override it i would get rid of defining

2022-03-04 20:37 UTC, sergeevds approved these changes

2022-03-05 12:16 UTC, Trevoule commented on react/src/components/Material/theme.js
> +  breakpoints: {
deleted

2022-03-06 09:50 UTC, merged